### ISSUE TITLE
Context menu “Add Item” does not work

### ISSUE THREAD

**Issue by sh2ezo** [Xtendia/FileCraft#13]
Hello! After last update context menu “Add Item” stopped working. When I try to launch command “File Craft: Add Item” manually, VS Code shows error: “command 'file-craft.addItem' not found”

**Comment by thefish1087** [comment]
Thank you so much for reporting the issues, and I'm so sorry you have to deal with that!

**Comment by sh2ezo** [comment]
Logs shows nothing. VS Code only reports error I posted above.
I think it is commit ea67704 that could break context menu because it changes a command registration code.

**Comment by thefish1087** [comment]
I have an idea of what could have gone wrong.
I'm working on it right now.

You said the log channel shows nothing. That means it is empty? Not even present? I am aware the log channel can not show such errors. I'm trying to know if the extension is properly activated.

**Comment by sh2ezo** [comment]
Do you mean “File Craft” has its own log channel? No, it is not present. If you want to know, what shows “extension host” about “file craft” - I will check it later.

**Comment by thefish1087** [comment]
Version 0.3.4 6ba825725825b5e0baddc1d9283138334ab99369 should fix your issue.
See the change-log for more information https://github.com/Xtendia/FileCraft/blob/main/CHANGELOG.md 

And, please let me know if the issue persist.

**Comment by sh2ezo** [comment]
Hello again!

- Original issue has been resolved by your fix.
- Output channel became visible too.

Many thanks!

**Comment by thefish1087** [comment]
Great news!

I hope you enjoy the new feature, Dynamic context menu:

They are now enable and disable accordingly to your workspace, if you have c# files, it shows the c# context menu, if you're working with Typescript, it shows typescript context menu, same for python and razor pages.

If you think you have an idea of a feature that can fit in the extension, a missing feature, or something, let me know. I'm enjoying so much working in this project, and see what I can do!

**Comment by thefish1087** [comment]
Thanks a lot!
