### ISSUE TITLE
Wrong namespace when C# project name contains dots

### ISSUE THREAD

**Issue by sh2ezo** [Xtendia/FileCraft#9]
Hello! When I create a class in a C# project that contains dots in its name, this dots are removed from namespace, inserted into resulting file

**Comment by thefish1087** [comment]
This behavior can be changed in the settings
Please open up the `vs code` settings and search for `File-craft` or `File craft` and in the `Namespace:Normalize` configuration, select `Do Nothing` instead of remove.

**Comment by sh2ezo** [comment]
It helped. Thank you!

**Comment by thefish1087** [comment]
Thanks for letting me know!
I will change the default to `Do nothing` next patch.
If you have more questions, or suggestions, feel free to raise another issue!
If you have a minute, please rate the extension on the marketplace.
